import NumStability.Source.Higham.Chapter04.Equation09

/-!
# Higham equation (4.9) source-entry-point smoke test
-/

#check NumStability.not_fl_kahanSum_biasedSmallCounterexample_twoStep_forward_bound_of_Cu_le_half
#check NumStability.Higham49BareFPModelTwoTermSecondOrderBound
#check NumStability.not_exists_higham49BareFPModelTwoTermSecondOrderBound
#check NumStability.fl_kahanSum_forward_error_bound_correctedReturnedMajorant
#check NumStability.highamCh4_equation49_modelStrengthCorrection_bareFPModel
#check NumStability.highamCh4_equation48_finiteFamily_no_fixed_secondOrderConstant
#check NumStability.highamCh4_equation49_finiteFamily_no_fixed_secondOrderConstant
#check NumStability.kahanFF_kahanSum_forward_error
