name = "highamBenchExecution"
version = "0.2.0"

[[require]]
name = "numStability"
git = "https://github.com/AlexGeorgantzas/lean-numerical-stability.git"
rev = "4ec1ec874353010ad93cc0bb76370ac321da4681"
