name = "LeanFpAnalysis"
version = "0.1.0"
defaultTargets = ["LeanFpAnalysis"]
weakLeanArgs = ["-j", "1"]

[[lean_lib]]
name = "LeanFpAnalysis"

[[lean_exe]]
name = "leanfpanalysis"
root = "Main"

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.29.0"
