name = "numStability"
version = "0.1.0"
defaultTargets = ["NumStability"]
weakLeanArgs = ["-j", "1"]

[[lean_lib]]
name = "NumStability"

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.29.0"
