import NumStability.Source.Higham.Chapter06.Norms

/-!
# Higham Chapter 6 norms aggregate import smoke test
-/

#check NumStability.HighamProblem61NormQuotientWitness
#check NumStability.highamProblem65MonomialMatrix
#check NumStability.highamProblem69_frobenius_op2_bounds
#check NumStability.complexMatrixBlockShearOp2_eq_highamProblem610_sourceFormula
#check NumStability.mixedInverseAmbientRelativeAmplificationRadiusSup_tendsto_conditionNumberProduct_of_positive_radii
