import NumStability.Algorithms.LU.BlockLU

/-!
# Historical BlockLU old-only import smoke test

This test deliberately imports only the historical BlockLU path. It verifies
that Phase 12A extraction preserves representatives from every migrated
surface formerly declared by or available through that module, including the
safe reusable Phase 12B slices.
-/

#check NumStability.FirstOrderLe
#check NumStability.maxEntryNorm
#check NumStability.maxEntryNormRect
#check NumStability.blockMaxNorm
#check NumStability.IsBlockDiagDomCol
#check NumStability.BlockLUFactSpec
#check NumStability.BlockLUBackwardError
#check NumStability.MatMulFirstOrderSpec
#check NumStability.growthFactorEntry_sq_kappa_budget_le_of_growth_le_inv_ratio
#check NumStability.blockMatrixNonsingular_of_posDef_flat
#check NumStability.higham13_maxNorm_vecResidual_lift
#check NumStability.blockSchur
#check NumStability.blockLUOneStepL
#check NumStability.blockLUOneStepU
#check NumStability.blockLUOneStepL_blockMaxNorm_le_of_firstSplit_tail
#check NumStability.blockLUOneStepU_blockMaxNorm_le_of_firstRow_tail
#check NumStability.blockLUOneStep_blockMaxNorm_product_le_of_firstSplit_tail
#check NumStability.block_lu_one_step
#check NumStability.dhsBlockForwardConventionalSolution
#check NumStability.blockErrorDelta
#check NumStability.higham13_theta_conventional_isBigO_cubic

#check NumStability.activeBlockIndices13_8
#check NumStability.Algorithm13_3Implementation1LocalSpec
#check NumStability.block_diag_dom_growth_bound_step
#check NumStability.block_diag_dom_schur_inherit
#check NumStability.block_lu_solve_backward_error
#check NumStability.BlockLUFactSpec.eq_of_schurTail_unique_of_right_inverse
#check NumStability.growthFactorEntry_blockMatrixFirstSplitFlat_eq_blockMatrixFlatFin
#check NumStability.higham13_algorithm13_3_firstSplitStageHistoryGrowthFactor_le_two_of_product_bound_diag_update
#check NumStability.higham13_eq13_22_exists_blockLUFact_matrix_stage_history_product_from_multiplier_bounds_exact_kappa
#check NumStability.higham13_lemma13_10_conditional_bound
