import NumStability.Analysis.Norms

/-!
# Historical norms facade import smoke test

This is deliberately an old-only import. It verifies that the historical path
continues to expose representatives from all reusable owners and every
source-owned Higham Chapter 6 norm result.
-/

#check NumStability.CVec
#check NumStability.LpConjugateExponents
#check NumStability.IsComplexLinearForm
#check NumStability.VectorNormRatioSet
#check NumStability.ComplexVectorMap
#check NumStability.basisUpperTriangularizes
#check NumStability.IsMixedSubordinateNormValue
#check NumStability.MixedUnitImageNormSet
#check NumStability.CMatrix
#check NumStability.ComplexMatrixEigenvalueModulusSet
#check NumStability.complexMatrixLpNorm
#check NumStability.IsComplexMatrixSVD
#check NumStability.euclideanReVec
#check NumStability.ComplexMatrixFlatEntryNorm
#check NumStability.ComplexMatrixFixedOperatorIdealNorm
#check NumStability.IsComplexHadamardMatrix
#check NumStability.ComplexMatrixLpUnitNormSet
#check NumStability.MixedRelativeSingularDistanceSet
#check NumStability.MixedInverseRelativeAmplificationRadiusSet
#check NumStability.tendsto_const_mul_of_tendsto_zero_of_eventually_abs_le
#check NumStability.HighamProblem61NormQuotientWitness
#check NumStability.highamProblem65MonomialMatrix
#check NumStability.highamProblem69_frobenius_op2_bounds
#check NumStability.complexMatrixBlockShearOp2_eq_highamProblem610_sourceFormula
#check NumStability.mixedInverseAmbientRelativeAmplificationRadiusSup_tendsto_conditionNumberProduct_of_positive_radii
