import NumStability.Source.Higham.Chapter13

/-!
# Higham Chapter 13 source-entry-point smoke test
-/

#check NumStability.higham13_table13_1_col_bdd_product_family_from_source_norms
#check NumStability.higham13_eq13_25_implementation1_spd_family_from_partitioned_computation
#check NumStability.higham13_demmel_sharp_multiplier_of_spectral_interval
#check NumStability.blockErrorDelta
#check NumStability.blockErrorTheta_le_cubic_of_quadratic_constants
#check NumStability.higham13_theta_conventional_isBigO_cubic
