import NumStability.Source.Higham.CrossChapter

#check NumStability.higham3_5_noGuard_forward_error
#check NumStability.higham12_6_lu_solve_SolverWBound
#check NumStability.higham15_1_eq_7_31_practical_bound_bridge
