import NumStability.Source.Higham

/-!
# Canonical Higham entry-point smoke test
-/

#check NumStability.FloatingPointFormat.problem2_4_theorem2_3_nearest_finite
#check NumStability.higham8_8_printed_rowDominance_condSkeel_claim_false
#check NumStability.higham10_7_actual_algorithm_source_closed
#check NumStability.Ch11Closure.TriGrowthInv.higham11_7_bunch_tridiagonal_support_aware
#check NumStability.higham13_table13_1_col_bdd_product_family_from_source_norms
#check NumStability.recursiveSum_problem43_abs_error_bound
#check NumStability.problem44_outputs_exactly_Icc
#check NumStability.HighamChapter4KaoWang.higham43_computedBudget_ne_kaoWangExactCost_witness
#check NumStability.higham14_hadamardConditionNumberRaw_negative_one_counterexample
#check NumStability.higham17_problem17_1
#check NumStability.higham17_22_exists_blockForm_spectralRadius_lt_one_of_forall_orbit_tendsto
#check NumStability.higham20_eq20_32_Bplus_residual_eq_crossProjection
#check NumStability.higham24_theorem24_3_literal_forward_error_multiple_kappa_u
#check NumStability.higham25EigenRoundedResidual
#check NumStability.higham26ADCrudeSweep_nondecreasing
#check NumStability.eq26_8_linearized_forward_error
#check NumStability.higham3_5_noGuard_any_order_forward_error
