import NumStabilityTest.Worker.Ch09.Canonical.Theorem914DiagDominant
import NumStabilityTest.Worker.Ch09.Canonical.Theorem99ComplexClosure
import NumStabilityTest.Worker.Ch09.Compatibility.HighamChapter9Theorem914DiagDominant
import NumStabilityTest.Worker.Ch09.Compatibility.HighamChapter9Theorem99ComplexClosure
