import NumStabilityTest.Worker.Ch09.Canonical.DoolittleClosure
import NumStabilityTest.Worker.Ch09.Canonical.Section08
import NumStabilityTest.Worker.Ch09.Canonical.Section10
import NumStabilityTest.Worker.Ch09.Compatibility.HighamChapter9
import NumStabilityTest.Worker.Ch09.Compatibility.HighamChapter9DoolittleClosure
