import NumStability.Algorithms.QR.HouseholderQRSupport

#check NumStability.coxHigham_exactSignedPivotPanel_sequence_active_block_bound_of_initial_block_bound_of_swapped_active_max_pivot_of_leading_block_det_ne_zero
