import NumStability.Source.Higham.Chapter16.Section01.SylvesterEquation.ComplexSolvability.Vectorized

#check NumStability.H16_eq16_2_26_existsUnique_sylvesterVecCoeff_mulVec_of_pos_le_sylvesterSepInf
