import NumStability.Source.Higham.Chapter16.Section02.BartelsStewart.Equations04To08.HessenbergRounded

#check NumStability.Wave17.H16_eq16_7_sylvesterHessenbergShiftedColumn_roundedGEPP_backward_error
