import NumStability.Algorithms.Sylvester.Higham16Minimizers
import NumStability.Algorithms.Sylvester.Higham16Spectrum
import NumStability.Algorithms.Sylvester.Higham16VecNorm

#check NumStability.H16_eq16_15_exists_sylvesterBackwardError_minimizer_of_svdOptimalPerturbations
#check NumStability.H16_eq16_29_realQuasiSchur_strictBlockMap_computed_residual_budget
#check NumStability.H16_eq16_23_sylvester_first_order_bound_diagonal_of_vecCoeff_entrywise_abs_ge
