import NumStability.Algorithms.MatrixEquations.Sylvester.Solvers.ComplexSchur.All
import NumStability.Algorithms.MatrixEquations.Sylvester.Solvers.QuasiTriangularBartelsStewart.All
import NumStability.Algorithms.MatrixEquations.Sylvester.Solvers.TriangularBartelsStewart.All

#check NumStability.HasComplexRightEigenvalue
#check NumStability.IsAdjacentQuasiTriangularBlockFn
#check NumStability.Wave14.componentwise_residual_of_perturbed_mulVec
