import NumStability.Algorithms.Cholesky.Aasen118ReducedCh11Closure
import NumStability.Algorithms.Cholesky.AasenAdjacentPivotOperationalMiddleCh11
import NumStability.Algorithms.Cholesky.AasenAdjacentPivotResidualDomainCh11Discrepancy
import NumStability.Algorithms.Cholesky.AasenAdjacentPivotSourceResidualCh11Closure
import NumStability.Algorithms.Cholesky.AasenAdjacentPivotTridiagExecutorCh11Closure
import NumStability.Algorithms.Cholesky.AasenAdjacentPivotTridiagForwardCounterexampleCh11
import NumStability.Algorithms.Cholesky.AasenCoupledFpCh11Closure
import NumStability.Algorithms.Cholesky.AasenDirect118Ch11Closure
import NumStability.Algorithms.Cholesky.AasenDirectTridiagGEPPSolveCh11Closure
import NumStability.Algorithms.Cholesky.AasenFactorNormCh11Closure
import NumStability.Algorithms.Cholesky.AasenFactorResidualCh11Closure
import NumStability.Algorithms.Cholesky.AasenGrowthCh11Closure
import NumStability.Algorithms.Cholesky.AasenMiddleGEPPCh11Counterexample
import NumStability.Algorithms.Cholesky.AasenOriginalCoordinateCorrectionCh11
import NumStability.Algorithms.Cholesky.AasenPermutationSourceCorrectionCh11
import NumStability.Algorithms.Cholesky.AasenPrintedCoefficientAlgebraCh11Closure
import NumStability.Algorithms.Cholesky.AasenSourceSharpFactorResidualCh11Closure
import NumStability.Algorithms.Cholesky.AasenTheorem118ScalarEdgeCh11Discrepancy
import NumStability.Algorithms.Cholesky.AasenTridiagGEPPCh11Closure
import NumStability.Algorithms.Cholesky.AasenUnitOuterSolveCh11Closure
import NumStability.Algorithms.Cholesky.BlockLDLTAllOneByOnePrintedCh11Closure
import NumStability.Algorithms.Cholesky.BlockLDLTBunchTridiagonalCh11Closure
import NumStability.Algorithms.Cholesky.BlockLDLTMixedPivotCh11Closure
import NumStability.Algorithms.Cholesky.BlockLDLTSolveBackwardCh11Closure
import NumStability.Algorithms.Cholesky.BunchKaufmanSolveCh11Closure
import NumStability.Algorithms.Cholesky.BunchTridiagonalActualSolveCh11Closure
import NumStability.Algorithms.Cholesky.BunchTridiagonalFactorBoundCh11Closure
import NumStability.Algorithms.Cholesky.BunchTridiagonalGrowthCh11Closure
import NumStability.Algorithms.Cholesky.BunchTridiagonalGrowthInvariantCh11Closure
import NumStability.Algorithms.Cholesky.BunchTridiagonalHFactorCh11Closure
import NumStability.Algorithms.Cholesky.BunchTridiagonalSparseFactorCh11Closure
import NumStability.Algorithms.Cholesky.BunchTridiagonalSparseSolveCh11Closure
import NumStability.Algorithms.Cholesky.Higham11BunchActualSharpGrowthClosure
import NumStability.Algorithms.Cholesky.Higham11BunchExactTrace
import NumStability.Algorithms.Cholesky.Higham11BunchKaufmanActualSelector
import NumStability.Algorithms.Cholesky.Higham11BunchKaufmanExactGrowth
import NumStability.Algorithms.Cholesky.Higham11BunchKaufmanExactGrowthArithmetic
import NumStability.Algorithms.Cholesky.Higham11BunchKaufmanExactTrace
import NumStability.Algorithms.Cholesky.Higham11BunchKaufmanExplicitInverseSolve
import NumStability.Algorithms.Cholesky.Higham11BunchKaufmanExplicitInverseTerminalClosedForm
import NumStability.Algorithms.Cholesky.Higham11BunchKaufmanRoundedAccumulated
import NumStability.Algorithms.Cholesky.Higham11BunchKaufmanRoundedBridge
import NumStability.Algorithms.Cholesky.Higham11BunchKaufmanRoundedClosure
import NumStability.Algorithms.Cholesky.Higham11BunchKaufmanRoundedExecution
import NumStability.Algorithms.Cholesky.Higham11BunchKaufmanRoundedFactors
import NumStability.Algorithms.Cholesky.Higham11BunchKaufmanRoundedGlobal
import NumStability.Algorithms.Cholesky.Higham11BunchKaufmanRoundedGrowth
import NumStability.Algorithms.Cholesky.Higham11BunchKaufmanRoundedGrowthSolve
import NumStability.Algorithms.Cholesky.Higham11BunchKaufmanRoundedMiddleSolve
import NumStability.Algorithms.Cholesky.Higham11BunchKaufmanRoundedSolve
import NumStability.Algorithms.Cholesky.Higham11BunchKaufmanRoundedTerminal
import NumStability.Algorithms.Cholesky.Higham11BunchKaufmanRoundedTerminalClosedForm
import NumStability.Algorithms.Cholesky.Higham11BunchKaufmanSourceCorrection
import NumStability.Algorithms.Cholesky.Higham11BunchSharpGrowthBridge
import NumStability.Algorithms.Cholesky.Higham11BunchTraceHadamard
import NumStability.Algorithms.Cholesky.Higham11Chapter9ActualExecutorBridge
import NumStability.Algorithms.Cholesky.Higham11Chapter9BridgeClosure
import NumStability.Algorithms.Cholesky.Higham11RookExactTrace
import NumStability.Algorithms.Cholesky.Higham11RookExecutorAdapter
import NumStability.Algorithms.Cholesky.Higham11RookRoundedGap
import NumStability.Algorithms.Cholesky.Higham11RookSourceClosure
import NumStability.Algorithms.Cholesky.Higham11SkewActualSelector
import NumStability.Algorithms.Cholesky.Higham11SkewExactTrace
import NumStability.Algorithms.Cholesky.Higham11SkewSourceCorrection
import NumStability.Algorithms.Cholesky.TwoByTwoSchurStepCh11Closure
import NumStability.Algorithms.HighamChapter11

/-!
# Isolated historical Chapter 11 import smoke test

Compiles the 66 historical Chapter 11 candidate paths on their own.  The
already-migrated `Cholesky.BunchTridiagonalCapstoneCh11Closure` wrapper is
deliberately absent: it is existing compatibility context that the Chapter 11
contract never re-owns.
-/
