import LeanFpAnalysis.HDP

open LeanFpAnalysis.HDP

/-!
Executable lookup file for the HDP side of the library.

Run:

  lake env lean examples/HDPLibraryLookup.lean
-/

-- Convex geometry core
#check PairwiseNormBound
#check empiricalAverage
#check diam_le_of_pairwiseNormBound
#check pairwiseNormBound_of_diam_le
#check convex_combo_dist_le_pairwise
#check maurey_sum_deviation_sq
#check norm_sum_deviation_le

-- Appetizer theorems
#check caratheodory_finiteDimensional
#check approximate_caratheodory
#check approximate_caratheodory_unit
#check approximate_caratheodory_theorem_0_0_2
#check approximate_caratheodory_of_diam_le

-- Covering polytopes by balls
#check empiricalCenters
#check empiricalCenters_ncard_le
#check convexHull_covered_by_empiricalCenters
#check covering_polytopes_by_balls_param
#check convexHull_subset_iUnion_closedBall_empiricalCenters
#check one_div_sqrt_natCeil_one_div_sq_le
#check covering_polytopes_by_balls
#check covering_polytope_by_balls_named
#check unorderedEmpiricalCenters
#check unorderedEmpiricalCenters_ncard_le_choose
#check improved_covering_polytopes_by_balls_param
#check improved_covering_polytopes_by_balls
#check improved_covering_polytopes_by_balls_exists_C

-- Binomial bounds from Exercise 0.0.5
#check choose_lower_bound
#check choose_le_sum_range_choose
#check sum_range_choose_le_exp_mul_div
#check exercise_0_0_5_binomial_chain

-- Variance identities from Exercise 0.0.3
#check productWeight
#check productWeight_snoc
#check sum_productWeight
#check norm_sum_sq_of_pairwise_inner_zero
#check weighted_variance_sum_independent
#check weighted_variance_identity

-- Chapter 1, Section 1.1: random-variable notation and identities
#check expectation
#check expectation_def
#check momentGeneratingFunction
#check momentGeneratingFunction_eq_mgf
#check rawMoment
#check absoluteMoment
#check eAbsoluteMoment
#check lpNorm
#check lpNorm_top_eq_essSup_enorm
#check lpNorm_top_eq_essSup_abs
#check hdpMemLp
#check hdpLp
#check hdpMemLp_iff_memLp
#check hdpMemLp_iff_aestronglyMeasurable_and_eLpNorm_lt_top
#check hdpLp_completeSpace
#check hdpL2_real_innerProductSpace
#check hdpL2_real_completeSpace
#check l2Inner
#check l2Norm
#check l2Norm_eq_sqrt_absMoment
#check standardDeviation
#check variance_eq_expectation_sq_sub_mean
#check standardDeviation_sq
#check standardDeviation_eq_l2Norm_centered
#check covariance_eq_l2Inner_centered
#check centralMoment_two_eq_variance
#check distribution
#check cumulativeDistribution
#check upperTail
#check lowerTail
#check cumulativeDistribution_eq_distribution_Iic
#check upperTail_eq_one_sub_cdf
#check distribution_eq_of_cdf_eq
#check standardNormalDensity
#check standardNormalDensity_eq

-- Chapter 1, Section 1.2: inequalities and tail identities
#check jensen_integral
#check lpNorm_mono_exponent
#check minkowski_eLpNorm
#check holder_integral_mul_abs
#check holder_eLpNorm_one_top
#check holder_integral_mul_abs_one_top
#check cauchy_schwarz_integral_mul
#check integral_abs_le_sqrt_integral_sq
#check lintegral_identity_nonnegative_real
#check lintegral_identity_nonnegative_ennreal
#check lintegral_identity_nonnegative_ennreal_of_ae_lt_top
#check integral_identity_nonnegative
#check integral_identity_real
#check integral_identity_real_book_form
#check eAbsoluteMoment_eq_lintegral_tail
#check absoluteMoment_eq_integral_tail
#check absoluteMoment_eq_integral_tail_of_lintegral_tail_lt_top
#check markov_inequality
#check chebyshev_inequality

-- Chapter 1, Section 1.3: limit-theorem infrastructure
#check lawOf
#check partialSum
#check sampleMean
#check variance_sum_independent
#check variance_sampleMean_eq
#check expected_abs_sampleMean_sub_mean_le
#check exercise_1_3_3_expected_abs_sampleMean_sub_mean_isBigO
#check strong_law_large_numbers_real
#check standardNormalProbability
#check standardNormal_tail_eq_integral
#check normalizedSum
#check normalizedSum_eq_sum_centered
#check integral_partialSum_eq_sum_integral
#check integral_partialSum_eq_card_mul_mean
#check integral_normalizedSum_eq_zero
#check variance_normalizedSum_eq_one
#check centralLimitConclusion
#check centralLimit_tail_tendsto
#check centralLimit_tail_tendsto_integral
#check LindebergLevyCLTHypotheses
#check lindebergLevyCentralLimitTheoremStatement
#check bernoulliNatPMF
#check bernoulliNatPMF_apply_one
#check bernoulliNatPMF_apply_zero
#check bernoulliNatPMF_apply_of_ne_zero_one
#check measureReal_eq_one_of_hasLaw_bernoulliNatPMF
#check measureReal_eq_zero_of_hasLaw_bernoulliNatPMF
#check ae_eq_zero_or_one_of_hasLaw_bernoulliNatPMF
#check integral_coe_nat_eq_of_hasLaw_bernoulliNatPMF
#check memLp_coe_nat_of_hasLaw_bernoulliNatPMF
#check variance_coe_nat_eq_of_hasLaw_bernoulliNatPMF
#check bernoulliTrialVectorPMF
#check bernoulliTrialVectorPMF_toMeasure_eq_pi
#check bernoulliNatVectorPMF
#check bernoulliNatVectorPMF_toMeasure_eq_pi
#check bernoulliSuccessCount
#check bernoulliSuccessCountFin
#check bernoulliTrialVectorPMF_map_successCountFin_eq_binomial
#check bernoulliSumPMF
#check bernoulliSumPMF_eq_binomialNatPMF
#check bernoulliNatVectorPMF_map_sum_eq_binomialNatPMF
#check hasLaw_sum_bernoulliNatPMF_eq_binomialNatPMF_of_jointLaw
#check hasLaw_sum_bernoulliNatPMF_eq_binomialNatPMF
#check integral_eq_of_real_bernoulli
#check variance_eq_of_real_bernoulli
#check binomialNatPMF
#check poissonPointProbability
#check poissonPointProbability_eq
#check poissonProbabilityMeasure
#check poissonProbabilityMeasure_singleton
#check poissonTriangularSum
#check rowParameterSum
#check rowParameterMax
#check poissonLimitConclusion
#check PoissonLimitTheoremHypotheses
#check poissonLimitTheoremStatement
#check probabilityMeasure_nat_tendsto_of_singleton
#check poisson_limit_of_point_probabilities
