import LeanFpAnalysis.FP

open LeanFpAnalysis.FP

/-!
This file is a small executable index for library exploration.
Run it with:

  lake env lean examples/LibraryLookup.lean

It intentionally contains no task-specific proof scripts.
-/

-- Floating-point model and gamma calculus
#check FPModel
#check gamma
#check gammaValid
#check gammaValid_mono
#check gamma_nonneg
#check gamma_mono
#check prod_error_bound
#check gamma_mul
#check gamma_inv
#check gamma_div
#check gamma_sum_le

-- General error and stability definitions
#check absError
#check relError
#check backwardErrorBounded
#check backwardErrorBoundedVec
#check relBackwardErrorBounded2
#check isRelComponentwiseBackwardStable
#check forward_from_backward

-- Finite probability and concentration kernels
#check FiniteProbability
#check FiniteProbability.eventProb
#check FiniteProbability.expectationNat
#check FiniteProbability.expectationReal
#check FiniteProbability.eventProb_nonneg
#check FiniteProbability.eventProb_mono
#check FiniteProbability.eventProb_univ
#check FiniteProbability.eventProb_add_le_eventProb_inter_add_one
#check FiniteProbability.eventProb_inter_ge_one_sub_add
#check FiniteProbability.expectationReal_mono
#check FiniteProbability.abs_expectationReal_le_expectationReal_abs
#check FiniteProbability.expectationReal_sq_le_expectationReal_sq
#check FiniteProbability.expectationReal_le_sqrt_expectationReal_sq
#check FiniteProbability.eventProb_real_ge_le_expectationReal_div
#check FiniteProbability.eventProb_real_le_ge_one_sub_expectationReal_div
#check FiniteProbability.eventProb_le_ge_one_sub_expectationReal_sq_div
#check FiniteProbability.eventProb_nat_le_ge_one_sub_expectationNat_div_succ
#check FiniteProbability.eventProb_abs_sub_le_ge_one_sub_of_second_moment
#check FiniteProbability.eventProb_nat_ge_le_exp_mul_mgf
#check FiniteProbability.eventProb_nat_le_ge_one_sub_chernoff_of_mgf_bound

-- Summation and dot products
#check fl_sum_error
#check fl_sum_error_init
#check fl_sum_error_tight
#check fl_dotProduct
#check dotProduct_error_bound
#check dotProduct_backward_error
#check dotProduct_backward_stable_x
#check dotProduct_backward_stable_y
#check dotProduct_isRelBackwardStable

-- Matrix-vector and matrix-matrix products
#check fl_matVec
#check matVec_backward_error
#check matVec_error_bound
#check matVec_row_isRelBackwardStable
#check fl_matMul
#check matMul_error_bound
#check matMul_backward_error_col
#check outerProduct_error_bound
#check outerProduct_backward_error
#check frobNorm_le_of_entry_abs_le

-- RandNLA element-wise sampling
#check sqMagProb
#check sqMagProb_sum_eq_one
#check elementwiseSampleUpdate
#check ElementwiseTrace
#check hitCount
#check elementwiseTraceSketch
#check fl_elementwiseTraceSketch
#check elementwiseTraceSketch_eq_repeat_of_hitCount
#check fl_elementwiseTraceSketch_eq_repeat_of_hitCount
#check fl_elementwiseUpdateEntry_error_bound
#check fl_elementwiseUpdateEntry_sqMag_error_bound
#check fl_repeatElementwiseUpdateEntry_error_bound
#check fl_repeatElementwiseUpdateEntry_sqMag_error_bound
#check fl_elementwiseTraceSketch_error_bound
#check elementwiseTraceSketch_sqMag_eq
#check fl_elementwiseTraceSketch_sqMag_error_bound
#check fl_elementwiseTraceSketch_sqMag_error_bound_exact
#check fl_elementwiseSketch_zero_init_sqMag_error_bound
#check fl_elementwiseTraceSketch_entrywise_sqMag_error_bound
#check sqMagTraceErrorBudget
#check sqMagTraceErrorBudget_mono
#check fl_elementwiseTraceSketch_sqMag_error_bound_of_hitCount_le
#check hitCountAtMostEvent
#check sqMagTraceStabilityEvent
#check hitCountAtMostEvent_subset_sqMagTraceStabilityEvent
#check probability_sqMagTraceStability_of_hitCount_concentration
#check highProbability_sqMagTraceStability_of_hitCount_concentration
#check hitIndicator
#check hitCount_eq_sum_indicator
#check expectationNat_hitCount_eq_sum_step_hit_probs
#check expectationNat_hitCount_eq_steps_mul_hitProb
#check expectationReal_hitCount_centered_sq_eq_pairwise
#check hitCount_concentration_markov_of_marginal_hitProb
#check hitCount_concentrates_of_marginal_hitProb
#check hitCount_concentration_sqMag_markov
#check hitCount_concentrates_sqMag
#check markovHitCountBudget
#check sqMagMarkovHitCountBudget
#check chebyshevHitCountBudget
#check sqMagChebyshevHitCountBudget
#check sampleHitIndicator
#check sqMagTraceProbMass
#check sqMagTraceProbability
#check sqMagTraceProbability_expectationReal_exp_hitCount_eq
#check sqMagTraceProbability_chernoff_mgf_bound
#check hitCountChernoffMGFBound
#check sqMagHitCountChernoffMGFBound
#check hitCount_concentrates_sqMag_chernoff_of_mgf_bound
#check hitCount_concentrates_sqMag_chernoff_optimized_of_mgf_bound
#check chernoffHitCountTail
#check sqMagChernoffHitCountTail
#check chernoffHitCountBudget
#check sqMagChernoffHitCountBudget
#check chernoffOptimizedHitCountTail
#check sqMagChernoffOptimizedHitCountTail
#check hitCount_concentrates_sqMag_around_mean_pairwise
#check hitCount_concentrates_sqMag_chernoff_independent
#check hitCount_concentrates_sqMag_chernoff_independent_budget
#check hitCount_concentrates_sqMag_chernoff_optimized_independent
#check hitCount_concentrates_sqMag_chernoff_optimized_independent_of_tail_budget
#check highProbability_sqMagTraceStability_of_marginal_hitProb
#check highProbability_sqMagTraceStability_of_marginal_hitProb_of_tail_budget
#check highProbability_sqMagTraceStability_of_pairwise_hitCount_deviation
#check highProbability_sqMagTraceStability_of_markov_budget
#check highProbability_sqMagTraceStability_of_pairwise_chebyshev_budget
#check highProbability_sqMagTraceStability_of_independent_chernoff_budget
#check highProbability_sqMagTraceStability_of_independent_chernoff_optimized_tail_budget
#check TraceValidForSqMag
#check fl_elementwiseTraceSketch_all_hit_sqMag_error_bound

-- RandNLA row sampling
#check rowNormSq
#check rowSqNormProb
#check rowSqNormProb_sum_eq_one
#check RowTrace
#check rowSampleScaleDen
#check rowSampleScaleDen_ne_zero
#check rowSampleIncrement
#check fl_rowSampleIncrement
#check fl_rowSampleIncrement_error_bound
#check rowSampleSketch
#check fl_rowSampleSketch
#check fl_rowSampleSketch_error_bound
#check rowSqNormTraceProbMass
#check rowSqNormTraceProbMass_sum_eq_one
#check rowSqNormTraceProbability
#check rowGram
#check rowSketchGram
#check rowSampleGram
#check fl_rowSampleGram
#check rowOuterGramSample
#check rowSqNormTraceProbability_expectationReal_rowSampleGram_entry
#check rowSqNormTraceProbability_expectationReal_rowSampleGram_frob_error_sq_le
#check rowSqNormTraceProbability_expectationReal_rowSampleGram_frob_error_le
#check rowSqNormTraceProbability_eventProb_rowSampleGram_frob_error_le_epsilon
#check rowSqNormTraceProbability_eventProb_rowSampleGram_frob_error_le_epsilon_of_budget
#check rowSampleGram_entry_error_bound_of_entrywise
#check rowSampleGram_frob_error_bound_of_entrywise
#check rowSqNormTraceProbability_expectationReal_rowSketchGram_entry_bias_bound_of_entrywise
#check rowSqNormTraceProbability_expectationReal_fl_rowSampleGram_entry_bias_bound_of_entrywise
#check rowSqNormTraceProbability_expectationReal_rowSketchGram_frob_error_le_add_perturb
#check rowSqNormTraceProbability_expectationReal_fl_rowSampleGram_frob_error_le_add_perturb
#check rowSqNormTraceProbability_eventProb_rowSketchGram_frob_error_le_epsilon_add_tau
#check rowSqNormTraceProbability_eventProb_fl_rowSampleGram_frob_error_le_epsilon_add_tau
#check rowSqNormTraceProbability_eventProb_fl_rowSampleGram_frob_error_le_epsilon_add_tau_of_forall
#check rowSqNormTraceProbability_eventProb_fl_rowSampleGram_frob_error_le_epsilon_add_tau_of_entrywise_budget

-- Triangular solves
#check fl_forwardSub
#check forwardSub_backward_error
#check fl_backSub
#check backSub_backward_error
#check triangularSolve_backward_error
#check backSub_forward_error
#check forwardSub_forward_error

-- LU and Cholesky solve contracts
#check LUBackwardError
#check lu_backward_error_gamma
#check lu_solve_backward_error
#check lu_solve_backward_error_tight
#check CholeskyBackwardError
#check cholesky_backward_error_perturbation
#check cholesky_solve_backward_error_expanded
#check cholesky_solve_backward_error

-- Residuals, refinement, and stationary iteration
#check fl_residual
#check ResidualError
#check SolverSpec
#check conventional_residual_error
#check one_step_refinement_error_identity
#check one_step_residual_bound
#check lu_refinement_backward_stable
#check normwise_forward_bound
#check main_forward_bound
#check normwise_residual_bound

-- Exact matrix algebra and perturbation theory
#check matMul_id_right
#check matMul_id_left
#check matMul_assoc
#check matMul_vec_eq
#check matMulVec_matMul
#check forward_error_from_residual
#check componentwise_forward_error
#check forward_error_from_backward_error
#check normwise_forward_error_exact
