import NumStability.Higham.Chapter20.SourceAliases

/-!
# Historical Higham Chapter 20 source-alias import smoke test
-/

#check NumStability.higham20_eq20_32_Bplus_residual_eq_crossProjection
#check NumStability.higham20_lemma20_6_exists_symmetric_perturbation_minimizer_and_norm_bounds
#check NumStability.higham20_theorem20_1_solution_and_residualRelativeRHS_le_of_one_rhs_budget
