import NumStability.Algorithms

/-!
# Algorithms entry-point smoke test

Checks representative arithmetic, factorization, and randomized-linear-
algebra declarations through the historical Algorithms aggregate.
-/

#check NumStability.fl_recursiveSum
#check NumStability.fl_noGuardDotProduct
#check NumStability.recursiveSum_problem43_abs_error_bound
#check NumStability.fl_pairwiseSumSixDisplayed
#check NumStability.higham24_theorem24_3_literal_forward_error_multiple_kappa_u
#check NumStability.higham25NewtonEquation
#check NumStability.OrthogonalSequenceBackwardError
#check NumStability.RectRankFactorization
#check NumStability.highamCh4_equation48_finiteFamily_no_fixed_secondOrderConstant
#check NumStability.highamCh4_equation49_finiteFamily_no_fixed_secondOrderConstant
#check NumStability.problem44_outputs_exactly_Icc
#check NumStability.HighamChapter4KaoWang.higham43_computedBudget_ne_kaoWangExactCost_witness
#check NumStability.higham17_problem17_1
#check NumStability.higham17_22_exists_blockForm_spectralRadius_lt_one_of_forall_orbit_tendsto
#check NumStability.higham12_problem12_2_two_step_recurrence
#check NumStability.higham13_demmel_sharp_multiplier_of_spectral_interval
#check NumStability.Ch22B.ch22bComplexConfluent_theorem12_3_exact_q_bound
#check NumStability.higham27_problem27_6_cubic_error_bound
#check NumStability.StrassenRecurrence
#check NumStability.higham23_winogradStrassen_error_step
#check NumStability.higham23_theorem23_2_strassen_closedCoefficient_firstOrder
#check NumStability.higham23_theorem23_3_winograd_closedCoefficient_firstOrder
#check NumStability.higham23_eq23_11_miller_normwise
#check NumStability.higham23_biniLotti_scaledRemainder_isBigO_u_sq
#check NumStability.higham23_threeMStrassen_sourceCoefficient
#check NumStability.higham23_problem23_8_power_exponent
#check NumStability.higham26ADCrudeSweep_nondecreasing
#check NumStability.eq26_8_linearized_forward_error
#check NumStability.higham14SchulzStep
#check NumStability.Ch14Ext.ch14ext_schulzIter_tendsto_inverse_of_lt_two_div_norm_sq
#check NumStability.ch14ext_problem14_13_gej_bound_fin_one
#check NumStability.higham21Cond2With_row_scaling
#check NumStability.integral_abs_standardGaussian_difference
