import NumStability.Algorithms

/-!
# Algorithms entry-point smoke test

Checks representative arithmetic, factorization, and randomized-linear-
algebra declarations through the historical Algorithms aggregate.
-/

#check NumStability.fl_recursiveSum
#check NumStability.fl_noGuardDotProduct
#check NumStability.recursiveSum_problem43_abs_error_bound
#check NumStability.fl_pairwiseSumSixDisplayed
#check NumStability.higham24_theorem24_3_literal_forward_error_multiple_kappa_u
#check NumStability.higham25NewtonEquation
#check NumStability.OrthogonalSequenceBackwardError
#check NumStability.RectRankFactorization
#check NumStability.highamCh4_equation48_finiteFamily_no_fixed_secondOrderConstant
#check NumStability.highamCh4_equation49_finiteFamily_no_fixed_secondOrderConstant
#check NumStability.problem44_outputs_exactly_Icc
#check NumStability.HighamChapter4KaoWang.higham43_computedBudget_ne_kaoWangExactCost_witness
#check NumStability.higham17_problem17_1
#check NumStability.higham17_22_exists_blockForm_spectralRadius_lt_one_of_forall_orbit_tendsto
#check NumStability.higham26ADCrudeSweep_nondecreasing
#check NumStability.eq26_8_linearized_forward_error
