import NumStability.Analysis

/-!
# Analysis entry-point smoke test

Checks the canonical reusable analysis families and the source-correspondence
re-exports retained to preserve the historical `import NumStability.Analysis`
surface. Isolated import tests exercise the narrower canonical paths directly.
-/

#check NumStability.RoundoffFamily
#check NumStability.FirstOrderLe
#check NumStability.maxEntryNormRect
#check NumStability.norm_pow_le_two_mul_numericalRadius_pow
#check NumStability.higham18_kreiss_two_sided_proved
#check NumStability.semiconvergent_block_form_exists_of_convergence_real_spectrum
#check NumStability.higham17_22_exists_blockForm_spectralRadius_lt_one_of_forall_orbit_tendsto
#check NumStability.complexSylvesterOp
#check NumStability.not_forall_ieeeDoubleKahanStoredGridError_eq_on_source_grid
#check NumStability.integral_abs_standardGaussian_difference
#check NumStability.finUniformProbability
#check NumStability.orbit_halfOpenArc_frequency_tendsto
#check NumStability.problem2_11_decimalLeadingDigit
#check NumStability.problem2_11_empiricalDigitProbability
#check NumStability.logarithmicLeadingDigitMass
#check NumStability.orbit_mem_decimalDigitArc_iff
#check NumStability.CVec
#check NumStability.LpConjugateExponents
#check NumStability.IsComplexLinearForm
#check NumStability.VectorNormRatioSet
#check NumStability.ComplexVectorMap
#check NumStability.basisUpperTriangularizes
#check NumStability.IsMixedSubordinateNormValue
#check NumStability.MixedUnitImageNormSet
#check NumStability.CMatrix
#check NumStability.ComplexMatrixEigenvalueModulusSet
#check NumStability.complexMatrixLpNorm
#check NumStability.IsComplexMatrixSVD
#check NumStability.euclideanReVec
#check NumStability.ComplexMatrixFlatEntryNorm
#check NumStability.ComplexMatrixFixedOperatorIdealNorm
#check NumStability.IsComplexHadamardMatrix
#check NumStability.ComplexMatrixLpUnitNormSet
#check NumStability.MixedRelativeSingularDistanceSet
#check NumStability.MixedInverseRelativeAmplificationRadiusSet
#check NumStability.tendsto_const_mul_of_tendsto_zero_of_eventually_abs_le
#check NumStability.Ch14Ext.ch14ext_singularValue_abs_sub_le_of_euclideanLin_diff_bound
#check NumStability.HighamProblem61NormQuotientWitness
#check NumStability.highamProblem65MonomialMatrix
#check NumStability.highamProblem69_frobenius_op2_bounds
#check NumStability.complexMatrixBlockShearOp2_eq_highamProblem610_sourceFormula
#check NumStability.mixedInverseAmbientRelativeAmplificationRadiusSup_tendsto_conditionNumberProduct_of_positive_radii
#check NumStability.Lemma66.lemma66_a_frobenius_le
#check NumStability.higham6_doubleDualEvaluation_isGreatest
#check NumStability.ch6aside_maxNorm_not_consistent
#check NumStability.ch6aside_blockAntidiag_lp_eq
