import NumStability.Algorithms.LinearSystems.Triangular.Combined
import NumStability.FloatingPoint.OperationLaws
import NumStability.Higham.Chapter02.Problem04
import NumStability.Higham.Chapter02.Problem07
import NumStability.Higham.Chapter02.Problem22
import NumStability.Higham.Chapter13.Table13_1
import NumStability.Higham.Chapter14.Discrepancies
import NumStability.Higham.Chapter20.SourceAliases

/-!
# Canonical endpoint-path smoke test

Every canonical endpoint target is imported directly, independently of the
historical forwarding paths.
-/

#check NumStability.higham14_hadamardConditionNumberRaw_negative_one_counterexample
#check NumStability.higham13_table13_1_col_bdd_product_family_from_source_norms
#check NumStability.higham20_eq20_32_Bplus_residual_eq_crossProjection
#check NumStability.triangularSolve_backward_error
#check NumStability.problem2_22_guard_digit_a_sub_b_exact
#check NumStability.FloatingPointFormat.problem2_4_theorem2_3_nearest_finite
#check NumStability.FloatingPointFormat.finiteRoundToEvenOp_add_comm
#check NumStability.FloatingPointFormat.problem2_7_statement5_add_associativity_false
