import NumStability.Algorithms.Ch14Problem1413Boundary
import NumStability.Algorithms.Ch14SourceCorrections
import NumStability.Algorithms.LU.BlockLUTable13_1Families
import NumStability.Algorithms.LeastSquares.Higham20SourceAliases
import NumStability.Algorithms.TestMatrices.Higham28GaussianAbsoluteMoment
import NumStability.Algorithms.TriangularSolveCombined
import NumStability.Algorithms.Underdetermined.Higham21Condition
import NumStability.Analysis.Problem2_2
import NumStability.Analysis.Problem2_22
import NumStability.Analysis.Problem2_4
import NumStability.Analysis.Problem2_7

/-!
# Historical endpoint-path smoke test

The historical compatibility paths must expose the migrated declarations
without help from co-imported canonical modules.
-/

#check NumStability.higham14_hadamardConditionNumberRaw_negative_one_counterexample
#check NumStability.higham13_table13_1_col_bdd_product_family_from_source_norms
#check NumStability.higham20_eq20_32_Bplus_residual_eq_crossProjection
#check NumStability.triangularSolve_backward_error
#check NumStability.problem2_22_guard_digit_a_sub_b_exact
#check NumStability.FloatingPointFormat.problem2_4_theorem2_3_nearest_finite
#check NumStability.FloatingPointFormat.finiteRoundToEvenOp_add_comm
#check NumStability.FloatingPointFormat.problem2_7_statement5_add_associativity_false
#check NumStability.FloatingPointFormat.problem2_2_lemma2_1_spacing_bounds
#check NumStability.ch14ext_problem14_13_gej_bound_fin_one
#check NumStability.higham21Cond2With_row_scaling
#check NumStability.integral_abs_standardGaussian_difference
