import NumStability.Higham

/-!
# Higham correspondence entry-point smoke test

Ensure the historical Higham entry point forwards the complete canonical
`NumStability.Source.Higham` tree.
-/

#check NumStability.not_forall_ieeeDoubleKahanStoredGridError_eq_on_source_grid
#check NumStability.FloatingPointFormat.problem2_2_lemma2_1_spacing_bounds
#check NumStability.FloatingPointFormat.problem2_4_theorem2_3_nearest_finite
#check NumStability.ieeeNaiveMax_not_nan_propagating
#check NumStability.problem2_22_guard_digit_a_sub_b_exact
#check NumStability.recursiveSum_problem43_abs_error_bound
#check NumStability.problem44_outputs_exactly_Icc
#check NumStability.higham10_7_actual_algorithm_source_closed
#check NumStability.higham12_problem12_2_two_step_recurrence
#check NumStability.higham13_table13_1_col_bdd_product_family_from_source_norms
#check NumStability.higham13_demmel_sharp_multiplier_of_spectral_interval
#check NumStability.higham14_hadamardConditionNumberRaw_negative_one_counterexample
#check NumStability.ch14ext_problem14_13_gej_bound_fin_one
#check NumStability.higham17_problem17_1
#check NumStability.higham20_eq20_32_Bplus_residual_eq_crossProjection
#check NumStability.higham21Cond2With_row_scaling
#check NumStability.Ch22B.ch22bComplexConfluent_theorem12_3_exact_q_bound
#check NumStability.higham23_winogradStrassen_error_step
#check NumStability.higham23_problem23_8_power_exponent
#check NumStability.higham24_theorem24_3_literal_forward_error_multiple_kappa_u
#check NumStability.higham25NewtonEquation
#check NumStability.eq26_8_linearized_forward_error
#check NumStability.higham27_problem27_6_cubic_error_bound
#check NumStability.higham15_1_eq_7_31_practical_bound_bridge
#check NumStability.higham14SchulzStep
#check NumStability.Ch14Ext.ch14ext_schulzIter_tendsto_inverse_of_lt_two_div_norm_sq
