import NumStability.Higham

/-!
# Higham correspondence entry-point smoke test

Ensure the historical Higham entry point forwards the complete canonical
`NumStability.Source.Higham` tree.
-/

#check NumStability.FloatingPointFormat.problem2_4_theorem2_3_nearest_finite
#check NumStability.recursiveSum_problem43_abs_error_bound
#check NumStability.problem44_outputs_exactly_Icc
#check NumStability.higham10_7_actual_algorithm_source_closed
#check NumStability.higham13_table13_1_col_bdd_product_family_from_source_norms
#check NumStability.higham14_hadamardConditionNumberRaw_negative_one_counterexample
#check NumStability.higham17_problem17_1
#check NumStability.higham20_eq20_32_Bplus_residual_eq_crossProjection
#check NumStability.higham23_winogradStrassen_error_step
#check NumStability.higham23_problem23_8_power_exponent
#check NumStability.higham24_theorem24_3_literal_forward_error_multiple_kappa_u
#check NumStability.higham25NewtonEquation
#check NumStability.eq26_8_linearized_forward_error
#check NumStability.higham15_1_eq_7_31_practical_bound_bridge
