import NumStability.Source.Higham.Chapter04.Section02.KaoWangCitationDiscrepancy
import NumStability.Source.Higham.Chapter08.Lemma08Discrepancy
import NumStability.Source.Higham.Chapter10.Theorem07
import NumStability.Source.Higham.Chapter11.Theorem07
import NumStability.Source.Higham.Chapter17.Equation08
import NumStability.Source.Higham.Chapter17.Equation12
import NumStability.Source.Higham.Chapter17.Equation15
import NumStability.Source.Higham.Chapter17.Equation16
import NumStability.Source.Higham.Chapter17.Equation17
import NumStability.Source.Higham.Chapter17.Equation20
import NumStability.Source.Higham.Chapter17.Equation22
import NumStability.Source.Higham.Chapter17.Problem01
import NumStability.Source.Higham.Chapter23.BiniLotti.FirstOrder
import NumStability.Source.Higham.Chapter23.Equation11
import NumStability.Source.Higham.Chapter23.ErrorRecurrences
import NumStability.Source.Higham.Chapter23.Problem08
import NumStability.Source.Higham.Chapter23.Theorem02.ErrorBound
import NumStability.Source.Higham.Chapter23.Theorem03.ErrorBound
import NumStability.Source.Higham.Chapter23.ThreeMStrassen.FirstOrder
import NumStability.Source.Higham.Chapter26.AlternatingDirections.CrudeLineSearch
import NumStability.Source.Higham.Chapter26.Equation08
import NumStability.Source.Higham.Chapter26.IntervalArithmetic.DirectedRounding
import NumStability.Source.Higham.Chapter26.MultidirectionalSearch.RegularSimplex
import NumStability.Source.Higham.CrossChapter.LUSolverWeights.Doolittle
import NumStability.Source.Higham.CrossChapter.LUSolverWeights.Factorization
import NumStability.Source.Higham.CrossChapter.NoGuardDotProduct
import NumStability.Source.Higham.CrossChapter.PracticalConditionBound

/-!
# Canonical source-correspondence path smoke test

Every extracted source target is imported directly, independently of the
historical forwarding paths and the aggregate Higham entry point.
-/

#check NumStability.higham8_8_printed_rowDominance_condSkeel_claim_false
#check NumStability.higham10_7_fl_cholesky_success_source
#check NumStability.Ch11Closure.TriGrowthInv.higham11_7_bunch_tridiagonal_support_aware
#check NumStability.higham12_6_lu_solve_SolverWBound
#check NumStability.higham12_6_rectRoundedLoop_lu_solve_SolverWBound_source
#check NumStability.higham15_1_eq_7_31_practical_bound_bridge
#check NumStability.higham3_5_noGuard_any_order_forward_error
#check NumStability.HighamChapter4KaoWang.higham43_computedBudget_ne_kaoWangExactCost_witness
#check NumStability.higham17_problem17_1
#check NumStability.literal_norm_form_forward_bound
#check NumStability.literal_norm_form_jacobi_forward_bound
#check NumStability.literal_norm_form_sor_forward_bound
#check NumStability.literal_norm_form_gaussSeidel_forward_bound
#check NumStability.residualSigmaTsum_le_diagonalizable_max_bound_of_infNorm_bound
#check NumStability.higham17_22_exists_blockForm_spectralRadius_lt_one_of_forall_orbit_tendsto
#check NumStability.higham23_winogradStrassen_error_step
#check NumStability.higham23_theorem23_2_strassen_closedCoefficient_firstOrder
#check NumStability.higham23_theorem23_3_winograd_closedCoefficient_firstOrder
#check NumStability.higham23_eq23_11_miller_normwise
#check NumStability.higham23_biniLotti_scaledRemainder_isBigO_u_sq
#check NumStability.higham23_threeMStrassen_sourceCoefficient
#check NumStability.higham23_problem23_8_power_exponent
#check NumStability.higham26ADCrudeSweep_nondecreasing
#check NumStability.eq26_8_linearized_forward_error
#check NumStability.RealInterval.outwardMul_contains
#check NumStability.higham26RegularSimplex_other_edge_length
