import NumStability.Algorithms.FastMatMul.Higham23ThreeMStrassen

/-!
# Historical Chapter 23 import
-/

#check NumStability.StrassenErrorBound
#check NumStability.higham23_winogradStrassen_error_step
#check NumStability.higham23_theorem23_2_strassen_closedCoefficient_firstOrder
#check NumStability.higham23_theorem23_3_winograd_closedCoefficient_firstOrder
#check NumStability.higham23_eq23_11_miller_normwise
#check NumStability.higham23_biniLotti_scaledRemainder_isBigO_u_sq
#check NumStability.higham23_threeMStrassen_sourceCoefficient
