import NumStability.Higham.CrossChapter.Chapter02To03NoGuardDot

#check NumStability.fl_noGuardDotProduct
#check NumStability.SumTree.noGuard_backward_error
#check NumStability.higham3_5_noGuard_forward_error
