import NumStability.Analysis.Perturbation.LeastSquares.Equality.Perturbation

/-!
# Perturbation theory for equality-constrained least squares canonical-only import smoke test

Imports exactly one canonical module and checks representative public declarations.
-/

#check @NumStability.theorem20_8MaxRelativePerturbation
#check @NumStability.LSEFullRowRank.exists_theorem20_8_rank_tolerant_APplus_solution_difference_relative_le_firstOrderRHS_plus_eps_sq_coefficient_BAplus_residual_gap_small_gain_residualFactor_of_minimizers
#check @NumStability.IsLSEMinimizer.exists_unique_perturbed_lse_minimizer_and_rank_tolerant_source_residual_relative_solution_difference_and_sourceResidual_kkt_bound_with_perturbed_reduced_minimizer_orthogonal_of_maxRelativePerturbation_lseStackedFullColumnRank_rank_kkt_smallnessThreshold
