-- Algorithms/QR/HouseholderReflector.lean
--
-- Low-level Householder reflector construction helpers.
--
-- This file starts the reflector-construction layer below full QR.  It keeps
-- the distinction between:
--
--   * rounded construction data, such as a vector built using a rounded norm;
--   * the exact orthogonal Householder matrix associated with a nonzero vector.
--
-- That distinction matters: a rounded scalar β is not automatically the exact
-- scalar that makes I - βvvᵀ orthogonal.

import Mathlib.Data.Real.Basic
import Mathlib.Tactic.FieldSimp
import Mathlib.Tactic.Ring
import LeanFpAnalysis.FP.Algorithms.Norm2
import LeanFpAnalysis.FP.Algorithms.QR.HouseholderSpec

namespace LeanFpAnalysis.FP

open scoped BigOperators

-- ============================================================
-- §18.1  Low-level reflector construction helpers
-- ============================================================

/-- Exact sign choice used in Householder reflector construction.

    Comparisons and sign flips are treated as exact control/negation operations,
    not as rounded arithmetic. -/
noncomputable def householderSign (x : ℝ) : ℝ :=
  if 0 ≤ x then 1 else -1

theorem abs_householderSign (x : ℝ) : |householderSign x| = 1 := by
  unfold householderSign
  split <;> norm_num

theorem householderSign_mul_eq_abs (x : ℝ) :
    householderSign x * x = |x| := by
  unfold householderSign
  by_cases hx : 0 ≤ x
  · simp [hx, abs_of_nonneg hx]
  · have hxlt : x < 0 := lt_of_not_ge hx
    simp [hx, abs_of_neg hxlt]

/-- Exact scalar `β = 2/(vᵀv)` associated with a Householder vector. -/
noncomputable def exactHouseholderBeta (n : ℕ) (v : Fin n → ℝ) : ℝ :=
  2 / exactNorm2Sq n v

theorem exactHouseholderBeta_mul_norm2Sq (n : ℕ) (v : Fin n → ℝ)
    (hv : exactNorm2Sq n v ≠ 0) :
    exactHouseholderBeta n v * exactNorm2Sq n v = 2 := by
  unfold exactHouseholderBeta
  field_simp [hv]

/-- The exact Householder matrix associated with a nonzero vector is
    orthogonal. -/
theorem exactHouseholder_orthogonal (n : ℕ) (v : Fin n → ℝ)
    (hv : exactNorm2Sq n v ≠ 0) :
    IsOrthogonal n (householder n v (exactHouseholderBeta n v)) := by
  apply householder_orthogonal
  simpa [exactNorm2Sq] using exactHouseholderBeta_mul_norm2Sq n v hv

/-- Floating-point scalar `α = -sign(x₀) * ‖x‖₂`.

    The sign and negation are exact; the norm is the rounded norm from
    `fl_norm2`. -/
noncomputable def fl_householderAlpha (fp : FPModel) (n : ℕ)
    (x : Fin (n + 1) → ℝ) : ℝ :=
  -(householderSign (x 0)) * fl_norm2 fp (n + 1) x

/-- Floating-point Householder vector construction from a column segment.

    For a vector `x`, this sets

      `v₀ = fl(x₀ - α)` and `vᵢ = xᵢ` for `i > 0`,

    where `α = -sign(x₀) * fl_norm2(x)`.  This is the first low-level
    construction layer; later theorems must prove the needed nonzero and
    perturbation properties before full QR can use it end-to-end. -/
noncomputable def fl_householderVector (fp : FPModel) (n : ℕ)
    (x : Fin (n + 1) → ℝ) : Fin (n + 1) → ℝ :=
  fun i => if i = 0 then fp.fl_sub (x i) (fl_householderAlpha fp n x) else x i

/-- Rounded scalar `β` computed from a Householder vector using a rounded
    dot product and rounded division.

    This is useful for modeling executable code, but it should not be assumed
    to make `I - βvvᵀ` exactly orthogonal without an additional proof or an
    exact-β bridge. -/
noncomputable def fl_householderBeta (fp : FPModel) (n : ℕ)
    (v : Fin n → ℝ) : ℝ :=
  fp.fl_div 2 (fl_norm2Sq fp n v)

/-- Exact orthogonal reflector associated with the rounded vector constructed
    from `x`.

    This is not the same object as the reflector formed with the rounded
    `fl_householderBeta`; it is the mathematically exact Householder reflector
    generated by the computed vector. -/
noncomputable def exactHouseholderFromRoundedVector (fp : FPModel) (n : ℕ)
    (x : Fin (n + 1) → ℝ) : Fin (n + 1) → Fin (n + 1) → ℝ :=
  let v := fl_householderVector fp n x
  householder (n + 1) v (exactHouseholderBeta (n + 1) v)

end LeanFpAnalysis.FP
