import NumStability.Algorithms.LinearSystems.LeastSquares.Basic
import NumStability.Algorithms.LinearSystems.LeastSquares.Refinement
import NumStability.Algorithms.LinearSystems.LeastSquares.RowSorting
import NumStability.Algorithms.LinearSystems.LeastSquares.TraceKernel
import NumStability.Analysis.Perturbation.LeastSquares.Basic
import NumStability.Analysis.Perturbation.LeastSquares.Contract
import NumStability.Analysis.Perturbation.LeastSquares.Equality.KKTInverse
import NumStability.Analysis.Perturbation.LeastSquares.Equality.MixedStability
import NumStability.Analysis.Perturbation.LeastSquares.MinimumNorm
import NumStability.Analysis.Perturbation.LeastSquares.NormalEquations
import NumStability.Analysis.Perturbation.LeastSquares.ResidualQuality
import NumStability.Analysis.Perturbation.LeastSquares.WeightedLimit
import NumStability.Source.Higham.Chapter20.Equations.WeightedLimit
import NumStability.Source.Higham.Chapter20.Examples.Condition
import NumStability.Source.Higham.Chapter20.MinimumNormBackwardError
import NumStability.Source.Higham.Chapter20.NormalEquations
import NumStability.Source.Higham.Chapter20.Prose.Quantitative
import NumStability.Source.Higham.Chapter20.Remaining
import NumStability.Source.Higham.Chapter20.Theorem03.ResidualQuality
import NumStability.Source.Higham.Chapter20.Theorem03.ZeroDeltaB
import NumStability.Source.Higham.Chapter20.Theorem04.Refinement
import NumStability.Source.Higham.Chapter20.Theorem07.ActualAssembly
import NumStability.Source.Higham.Chapter20.Theorem07.ActualBackSub
import NumStability.Source.Higham.Chapter20.Theorem07.ActualClosure
import NumStability.Source.Higham.Chapter20.Theorem07.ActualGrowth
import NumStability.Source.Higham.Chapter20.Theorem07.ActualRhs
import NumStability.Source.Higham.Chapter20.Theorem07.ActualTrace
import NumStability.Source.Higham.Chapter20.Theorem07.Contract
import NumStability.Source.Higham.Chapter20.Theorem07.Elimination
import NumStability.Source.Higham.Chapter20.Theorem07.QdR
import NumStability.Source.Higham.Chapter20.Theorem07.RowPolicy
import NumStability.Source.Higham.Chapter20.Theorem07.Runtime
import NumStability.Source.Higham.Chapter20.Theorem07.SourceTrace
import NumStability.Source.Higham.Chapter20.Theorem08
import NumStability.Source.Higham.Chapter20.Theorem10

/-!
# Wave 7 axiom probes

Representative public declarations from each destination this wave created or
extended. Every probe must report only the accepted axiom set
`[propext, Classical.choice, Quot.sound]`.
-/

#print axioms NumStability.higham20_vecNorm2_le_sum_abs
#print axioms NumStability.higham20Eq20_4Q
#print axioms NumStability.Higham20EliminationActual.exactPivotedQRSwapSeq_fix_prefix
#print axioms NumStability.Theorem20_7.applyProd_sub
#print axioms NumStability.Higham20RowSorting.abs_householderBeta_mul_inner_trailingPart_le_sqrt_two_mul
#print axioms NumStability.Theorem20_7.householder_multiplier_le_sqrt_two_mul
#print axioms NumStability.Theorem20_8.kktLocalSmallnessCoeff_ge_one
#print axioms NumStability.Theorem20_10.fullConstraintUnitRoundoffSmallnessThreshold_pos
#print axioms NumStability.lsMinimumNormBackwardErrorValuesF.bddBelow
#print axioms NumStability.higham20NormalEqAbsRhs_vecNorm2_le
#print axioms NumStability.higham20_qr_norm_bounds_to_componentwise
#print axioms NumStability.lseWeightedMinimizer_energy_le_lagrange
#print axioms NumStability.vecNorm2Sq_lseStackedMatrix_mulVec
#print axioms NumStability.higham20_delta_example_A_op2_eq_one
#print axioms NumStability.higham20_p404_square_source_discrepancy
#print axioms NumStability.higham20_cholesky_R_frob_sq_le_source
#print axioms NumStability.higham20_cond2Transpose_le_card_mul_kappa2
#print axioms NumStability.higham20_eq20_11_fl_cholesky
#print axioms NumStability.Theorem20_3.gamma_tilde_mn_nonneg
#print axioms NumStability.Theorem20_3_ZeroDeltaB.stack_top
#print axioms NumStability.higham20Eq20_16_append_split
#print axioms NumStability.Theorem20_7.higham19_6_sourceConstructed_actual_closed
#print axioms NumStability.Theorem20_7.higham20_7_sourceConstructed_actual_closed
#print axioms NumStability.Theorem20_7.scale_le_pow_mul_of_step
#print axioms NumStability.Theorem20_7.sourceConstructedPivotedStoredQRSigma_succ_le
#print axioms NumStability.Theorem20_7.fl_sourceConstructedPivotedStoredQRRhsSeq_succ
#print axioms NumStability.Theorem20_7.sourceConstructedPivotedStoredQRPseq_orthogonal
#print axioms NumStability.Theorem20_7.rawRowCounter_A1_00
#print axioms NumStability.Higham20EliminationActual.pivotDAacc_zero
#print axioms NumStability.Theorem20_7.pivotedStoredQR_QdR_entrywise_le
#print axioms NumStability.Higham20RowSorting.exactASeq_succ
#print axioms NumStability.Theorem20_7.pivotedStoredQRRuntimeBeta_nonneg
#print axioms NumStability.Theorem20_7.fl_sourcePivotedStoredQRRhsSeq_zero
#print axioms NumStability.Theorem20_8.dataCoeff_nonneg
#print axioms NumStability.Theorem20_10.computedX_partA_certificate
