import NumStability.Algorithms.LinearSystems.LeastSquares.AugmentedSystem
import NumStability.Algorithms.LinearSystems.LeastSquares.Basic
import NumStability.Algorithms.LinearSystems.LeastSquares.GramBasis
import NumStability.Algorithms.LinearSystems.LeastSquares.MGS
import NumStability.Algorithms.LinearSystems.LeastSquares.NormalEquations
import NumStability.Algorithms.LinearSystems.LeastSquares.QRSolve
import NumStability.Algorithms.LinearSystems.LeastSquares.RankGeometry
import NumStability.Algorithms.LinearSystems.LeastSquares.StoredQR
import NumStability.Analysis.Perturbation.LeastSquares.AugmentedSystem
import NumStability.Analysis.Perturbation.LeastSquares.BackwardError
import NumStability.Analysis.Perturbation.LeastSquares.Basic
import NumStability.Analysis.Perturbation.LeastSquares.GramBasis
import NumStability.Analysis.Perturbation.LeastSquares.NormalEquations
import NumStability.Analysis.Perturbation.LeastSquares.Normwise
import NumStability.Analysis.Perturbation.LeastSquares.Projection
import NumStability.Source.Higham.Chapter20.Lemma11
import NumStability.Source.Higham.Chapter20.Lemma12
import NumStability.Source.Higham.Chapter20.Problem03
import NumStability.Source.Higham.Chapter20.Theorem03.QRSolve

/-!
# Wave 5 axiom probes

Representative public declarations from each destination this wave created or
extended. Every probe must report only the accepted axiom set
`[propext, Classical.choice, Quot.sound]`.
-/

#print axioms NumStability.lsScaledAugmentedMatrix_mulVec
#print axioms NumStability.lsVecNorm2Sq_append
#print axioms NumStability.rectRightGramBasisSingularValue_pos_of_rectMatMulVec_injective
#print axioms NumStability.MGSAugmentedLSFactorization
#print axioms NumStability.RectLSNormalEquations.of_permuteCols
#print axioms NumStability.storedHouseholderQRRhsSeq_zero
#print axioms NumStability.rectTopBlock_add
#print axioms NumStability.storedQRActiveMaxPivotColumn_pivotMax
#print axioms NumStability.lsScaledAugmentedDiagonalBranch_ne_zero_of_alpha_eq_div_sqrt_two
#print axioms NumStability.LSQRSolveBackwardError.of_rectangular_perturbed_normal_equations
#print axioms NumStability.ls_qr_forward_error
#print axioms NumStability.lsScaledAugmentedMatrix_kappa2_bounds_of_rightGram_basis_branch_data
#print axioms NumStability.rectLSGramPerturbation_eq_sum
#print axioms NumStability.lsNormwiseBackwardErrorCostF_sq
#print axioms NumStability.higham20_lemma20_12_rangeProjection_finrank_eq_matrixRank
#print axioms NumStability.higham20_lemma20_11_equalRank_pseudoinverse_op2_le
#print axioms NumStability.higham20_lemma20_12_equalRank_moorePenrose
#print axioms NumStability.RectMoorePenrosePseudoinverse.reverse
#print axioms NumStability.lsLemma20_6Projector_apply_vec
