import NumStability.Analysis.ProblemDependentStability

#check NumStability.HessenbergExactDiagTraceOnEntrywisePerturbation
#check NumStability.hessenbergDetExampleMatrix
#check NumStability.hessenbergDetExampleFirstMultiplier
