import NumStability.Analysis.Error

#check NumStability.AccuracyMeasure
#check NumStability.compRelError
#check NumStability.absError
#check NumStability.absError_nonneg
#check NumStability.absError_smul
#check NumStability.additiveUnderflowModelWitness
#check NumStability.additiveErrorWitness_of_signedRelErrorWitness
#check NumStability.noGuardAddWitness_alpha_bound
#check NumStability.NoGuardFPModel
#check NumStability.problem_1_1_relError_bounds
#check NumStability.ErrorSource
#check NumStability.abs_subtract_perturbed_error_le
#check NumStability.noGuardBinaryT3_exact_difference
